use mydb;

CREATE TABLE STUDENT
(SNO INT (5),
SNAME VARCHAR(15),
MARKS INT(3));

describe STUDENT;

/*Use of INSERT Command.*/
INSERT INTO STUDENT VALUES(101,'Tanmay',80);
INSERT INTO STUDENT(SNAME,SNO,MARKS) VALUES('Gopal',100,90);
INSERT INTO STUDENT VALUES(102,'Dhananjay',NULL);
INSERT INTO STUDENT VALUES(103,'Padmini',80);

SELECT * FROM STUDENT;

SELECT SNO NO, MARKS-20 M FROM STUDENT;

/*WHERE Command.*/
SELECT * FROM STUDENT WHERE MARKS IS NULL;
SELECT * FROM STUDENT WHERE SNO>100;
SELECT DISTINCT MARKS FROM STUDENT;

CREATE TABLE FACULTY
(FID INT (10),
 FNAME VARCHAR(15),
 FSALARY INT(8),
 FSUBJECT VARCHAR(15));
 
DESCRIBE FACULTY;

INSERT INTO FACULTY VALUES(501, 'Nitin', 10000, 'AM-2'); 
INSERT INTO FACULTY VALUES(503, 'Anne', 60000, 'PGM'); 
INSERT INTO FACULTY VALUES(504, 'Naveen', 80000, 'SE'); 

/*Use of WHERE & WHILED CARDS.*/ 
SELECT * FROM FACULTY; 
SELECT * FROM FACULTY WHERE FSALARY>50000; 
SELECT * FROM FACULTY WHERE FSALARY>50000 AND FSUBJECT='SE'; 
SELECT distinct FID FROM FACULTY; 
SELECT * FROM FACULTY WHERE FNAME LIKE '%e__'; 
 
CREATE TABLE DDL
(SID INT(4),SNAME VARCHAR(15));

DESCRIBE DDL; 

INSERT INTO DDL VALUES(101,'DAVID');
INSERT INTO DDL VALUES(102,'PAUL');
INSERT INTO DDL VALUES(103,'MEENA');
COMMIT;
SELECT * FROM DDL;

/*Use of ALTER Command*/
ALTER TABLE DDL ADD(GRADE VARCHAR(2));
ALTER TABLE DDL DROP COLUMN GRADE;
ALTER TABLE DDL MODIFY COLUMN SNAME VARCHAR(10); 
ALTER TABLE DDL RENAME COLUMN SNAME TO S_NAME;

/*By default value is 1, which commits all DML transactions automatically.*/
SET autocommit=0;

/*To perform transactions safely we need it.*/
SET sql_SAFE_UPDATES = 0;

/*Temporary deletes data but table structure remains same.*/
DELETE FROM DDL; 

/*To get the deleted data back.*/
ROLLBACK; 

/*As autocommit is 0.*/
COMMIT;

/*DELETES data permanently but table structure remains same.*/ 
TRUNCATE TABLE DDL; 

/*DROP is also used which deletes entire table structure with data permanently!*/

/*RENAMES TABLE.(DDL cmd)*/
RENAME TABLE DDL TO MOD_DDL; 
 
-- COMMIT & ROLLBACK ARE TCL COMMANDS.
 
 
 
 
 
 